### ISSUE TITLE
怎么打包呢？

### ISSUE THREAD

**Issue by chenweigh** [Lstmxx/vite-svg-plugin#11]
目前封装了svg-icon 来加载svg文件。
不知道怎么打包，供另一个项目使用

**Comment by Lstmxx** [comment]
有详细的demo吗？

**Comment by chenweigh** [comment]
暂时没有
我换这个库了vite-plugin-svg-icons 。这个库在vite.config.ts plugin配置后，执行 vite build 有_virtual  相关的svg。

`vite-svg-plugin` 按照文档配置，vite.config.ts plugin 后，执行vite build，去看打包内容，没有看到svg相关文件。
