### ISSUE TITLE
viewBox is not generated based on width and height of svg？

### ISSUE THREAD

**Issue by lyjk-underdog** [Lstmxx/vite-svg-plugin#4]
svg file：
![image](https://user-images.githubusercontent.com/60835132/190342218-4af707bb-e778-439f-8af0-74d5b53e9ec7.png)
vite config：
<img width="668" alt="1663227056026" src="https://user-images.githubusercontent.com/60835132/190342688-f57c3434-933e-415f-af4d-be041e4f9fce.png">
generated ：
<img width="499" alt="1663227098630" src="https://user-images.githubusercontent.com/60835132/190342837-44dd4ccb-4c77-403f-be61-0da35b6ed4d0.png">

**Comment by Lstmxx** [comment]
> svg file： ![image](https://user-images.githubusercontent.com/60835132/190342218-4af707bb-e778-439f-8af0-74d5b53e9ec7.png) vite config： <img alt="1663227056026" width="668" src="https://user-images.githubusercontent.com/60835132/190342688-f57c3434-933e-415f-af4d-be041e4f9fce.png"> generated ： <img alt="1663227098630" width="499" src="https://user-images.githubusercontent.com/60835132/190342837-44dd4ccb-4c77-403f-be61-0da35b6ed4d0.png">

Try this branch  [fix/viewbox-problem](https://github.com/Lstmxx/vite-svg-plugin/tree/fix/viewbox-problem), i just fix it.

**Comment by lyjk-underdog** [comment]
thanks ， it worked

**Comment by Lstmxx** [comment]
> thanks ， it worked

No thx :).
The package is published, please use v1.0.2
